=== SoftalkAppleProject/datasets_toc-masthead-adindex/ppg2leaf_map/MagazineGTS/schemas/factminers_magazine_issue_gts_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.factminers.org/MAGAZINE/gts/2017-02-14"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:gts="http://www.factminers.org/MAGAZINE/gts/2017-02-14">
	<element name="MAGAZINEissueGTS">
		<complexType>
			<sequence>
				<element ref="gts:Metadata"/>
				<element ref="gts:DocumentStructure"/>
				<element ref="gts:ContentDepiction"/>
			</sequence>
			<attribute name="MAGAZINEissueGTS_Id" use="required" type="NCName"/>
		</complexType>
	</element>
	<element name="Metadata">
		<complexType>
			<sequence>
				<element ref="gts:Creator"/>
				<element ref="gts:Created"/>
				<element ref="gts:LastChange"/>
				<element ref="gts:Comment"/>
			</sequence>
		</complexType>
	</element>
	<element name="Creator" type="string"/>
	<element name="Created" type="dateTime"/>
	<element name="LastChange" type="dateTime"/>
	<element name="DocumentStructure">
		<complexType>
			<sequence>
				<element ref="gts:Comment"/>
				<element ref="gts:DataSets"/>
			</sequence>
		</complexType>
	</element>
	<element name="ContentDepiction">
		<complexType>
			<sequence>
				<element ref="gts:Comment"/>
				<element ref="gts:ContentRelationships"/>
				<element ref="gts:DataSets"/>
			</sequence>
		</complexType>
	</element>
	<element name="ContentRelationships">
		<complexType>
			<sequence>
				<element ref="gts:Comment"/>
			</sequence>
		</complexType>
	</element>
	<element name="Comment" type="string"/>
	<element name="DataSets">
		<complexType>
			<choice>
				<sequence>
					<element ref="gts:People"/>
					<element ref="gts:Organizations"/>
					<element ref="gts:Products"/>
					<element ref="gts:Roles"/>
					<element ref="gts:StaffAssignments"/>
				</sequence>
				<sequence>
					<element ref="gts:ppg2leaf_map"/>
					<element ref="gts:TableOfContents"/>
					<element ref="gts:Masthead"/>
					<element ref="gts:Advertisements"/>
					<element ref="gts:FeatureArticles"/>
					<element ref="gts:Contest"/>
					<element ref="gts:Columns"/>
					<element ref="gts:BestSellerLists"/>
				</sequence>
			</choice>
		</complexType>
	</element>
	<element name="People">
		<complexType/>
	</element>
	<element name="Organizations">
		<complexType>
			<sequence>
				<element ref="gts:Companies"/>
				<element ref="gts:IndustryGroups"/>
				<element ref="gts:UserGroups"/>
			</sequence>
		</complexType>
	</element>
	<element name="Companies">
		<complexType/>
	</element>
	<element name="IndustryGroups">
		<complexType/>
	</element>
	<element name="UserGroups">
		<complexType/>
	</element>
	<element name="Products">
		<complexType>
			<sequence>
				<element ref="gts:Software"/>
				<element ref="gts:Hardware"/>
				<element ref="gts:Services"/>
				<element ref="gts:Other"/>
			</sequence>
		</complexType>
	</element>
	<element name="Software">
		<complexType/>
	</element>
	<element name="Hardware">
		<complexType/>
	</element>
	<element name="Services">
		<complexType/>
	</element>
	<element name="Other">
		<complexType/>
	</element>
	<element name="Roles">
		<complexType>
			<sequence>
				<element ref="gts:ContentReferenced"/>
				<element ref="gts:Advertisers"/>
				<element ref="gts:Authors"/>
				<element ref="gts:StaffPositions"/>
			</sequence>
		</complexType>
	</element>
	<element name="ContentReferenced">
		<complexType/>
	</element>
	<element name="Advertisers">
		<complexType>
			<sequence>
				<element ref="gts:Comment"/>
			</sequence>
		</complexType>
	</element>
	<element name="Authors">
		<complexType/>
	</element>
	<element name="StaffPositions">
		<complexType/>
	</element>
	<element name="StaffAssignments">
		<complexType>
			<sequence>
				<element ref="gts:Comment"/>
			</sequence>
		</complexType>
	</element>
	<element name="ppg2leaf_map">
		<complexType>
			<sequence>
				<element maxOccurs="unbounded" ref="gts:leaf"/>
			</sequence>
		</complexType>
	</element>
	<element name="leaf">
		<complexType>
			<sequence>
				<element ref="gts:pageNum"/>
				<element ref="gts:ocr_ppg"/>
				<element ref="gts:validation"/>
				<element ref="gts:pgType"/>
				<element ref="gts:handSide"/>
				<element ref="gts:issue_id"/>
				<element ref="gts:validated_on"/>
				<element ref="gts:validator"/>
			</sequence>
			<attribute name="leafnum" use="required" type="integer"/>
		</complexType>
	</element>
	<element name="pageNum" type="string"/>
	<element name="ocr_ppg" type="string"/>
	<element name="validation" type="string"/>
	<element name="pgType" type="string"/>
	<element name="handSide" type="string"/>
	<element name="issue_id" type="string"/>
	<element name="validated_on" type="string"/>
	<element name="validator" type="string"/>
	<element name="TableOfContents">
		<complexType/>
	</element>
	<element name="Masthead">
		<complexType/>
	</element>
	<element name="Advertisements">
		<complexType/>
	</element>
	<element name="FeatureArticles">
		<complexType/>
	</element>
	<element name="Contest">
		<complexType/>
	</element>
	<element name="Columns">
		<complexType>
			<sequence>
				<element ref="gts:OpenDiscussion"/>
				<element ref="gts:AssemblyLines"/>
			</sequence>
		</complexType>
	</element>
	<element name="OpenDiscussion">
		<complexType/>
	</element>
	<element name="AssemblyLines">
		<complexType/>
	</element>
	<element name="BestSellerLists">
		<complexType/>
	</element>
</schema>

=== SoftalkAppleProject/datasets_toc-masthead-adindex/ppg2leaf_map/MagazineGTS/softalkv4n11jul1984_magazine.xml
<?xml version="1.0" encoding="UTF-8"?>
<MAGAZINEissueGTS xmlns="http://www.factminers.org/MAGAZINE/gts/2017-02-14"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.factminers.org/MAGAZINE/gts/2017-02-14 http://www.factminers.org/MAGAZINE/gts/2017-02-14/factminers_magazine_issue_gts_schema.xsd"
	MAGAZINEissueGTS_Id="softalkv4n11jul1984">
	<Metadata>
		<Creator>FactMiners and The Softalk Apple Project</Creator>
		<Created>2017-02-14T12:00:00</Created>
		<LastChange>2017-02-14T12:00:00</LastChange>
		<Comment>MAGAZINE Ground Truth Storage for softalkv4n11jul1984 of the 48-issue run of Softalk Magazine.</Comment>
	</Metadata>
	<DocumentStructure>
		<Comment> This branch of the MAGAZINE #GTS format provides the metamodel and associated datasets
			that describe the complex document structure of this ISSUE of a magazine (or other serial publication). </Comment>
		<DataSets>
			<ppg2leaf_map>
				<leaf leafnum="1">
					<pageNum>Cover1</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Cover</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:23:57 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="2">
					<pageNum>Cover2</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>LEFT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:23:59 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="3">
					<pageNum>1</pageNum>
					<ocr_ppg>3</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:07 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="4">
					<pageNum>2</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Contents</pgType>
					<handSide>LEFT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:09 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="5">
					<pageNum>3</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Contents</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:11 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="6">
					<pageNum>4</pageNum>
					<ocr_ppg>4</ocr_ppg>
					<validation>printed</validation>
					<pgType>Normal</pgType>
					<handSide>LEFT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:12 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="7">
					<pageNum>5</pageNum>
					<ocr_ppg>7</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:14 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="8">
					<pageNum>6</pageNum>
					<ocr_ppg>6</ocr_ppg>
					<validation>printed</validation>
					<pgType>Normal</pgType>
					<handSide>LEFT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:15 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="9">
					<pageNum>7</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:17 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="10">
					<pageNum>8</pageNum>
					<ocr_ppg>8</ocr_ppg>
					<validation>printed</validation>
					<pgType>Normal</pgType>
					<handSide>LEFT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:18 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="11">
					<pageNum>9</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:19 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="12">
					<pageNum>10</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>LEFT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:20 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="13">
					<pageNum>11</pageNum>
					<ocr_ppg>11</ocr_ppg>
					<validation>printed</validation>
					<pgType>Normal</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:22 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="14">
					<pageNum>12</pageNum>
					<ocr_ppg>12</ocr_ppg>
					<validation>printed</validation>
					<pgType>Normal</pgType>
					<handSide>LEFT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:23 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="15">
					<pageNum>13</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:24 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="16">
					<pageNum>14</pageNum>
					<ocr_ppg>14</ocr_ppg>
					<validation>printed</validation>
					<pgType>Normal</pgType>
					<handSide>LEFT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:25 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="17">
					<pageNum>15</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:26 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="18">
					<pageNum>16</pageNum>
					<ocr_ppg>16</ocr_ppg>
					<validation>printed</validation>
					<pgType>Normal</pgType>
					<handSide>LEFT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:28 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="19">
					<pageNum>17</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:29 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="20">
					<pageNum>18</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>LEFT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:31 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="21">
					<pageNum>19</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:33 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="22">
					<pageNum>20</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>LEFT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:34 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="23">
					<pageNum>21</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:35 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="24">
					<pageNum>22</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>LEFT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:37 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="25">
					<pageNum>23</pageNum>
					<ocr_ppg>None</ocr_ppg>
					<validation>inferred</validation>
					<pgType>Normal</pgType>
					<handSide>RIGHT</handSide>
					<issue_id>softalkv4n11jul1984</issue_id>
					<validated_on>02/26/17 10:24:38 -0700</validated_on>
					<validator>Jim Salmons and Timlynn Babitsky</validator>
				</leaf>
				<leaf leafnum="26">
					<pageNum>24</pageNum>
					<ocr_ppg>24</ocr_ppg>
					<validation>printed</validation>
					<pgType>Normal</pgType>
					<handSide>LEFT</handSide>
